name: Doxygen Docs

on:
  push:
    tags:
      - 'v*'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Upload Docs
        uses: actions/upload-artifact@v2.3.1
        with:
          name: doxygen-docs
          path: docs/html
