name: Generate Doxygen Docs

on:
  push:
    tags:
      - 'v*'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v3
        with:
          name: doxygen-docs
          path: docs/html
